_target_: topotein.features.factory.TopoteinFeaturiser
representation: CA
scalar_node_features:
  - amino_acid_one_hot
  - sequence_positional_encoding
  - alpha
  - kappa
  - dihedrals
  - sidechain_torsions
  - secondary_structure_one_hot
vector_node_features: []
edge_types:
  - knn_16
scalar_edge_features:
  - edge_distance
vector_edge_features: []
sse_types:
  - H
  - E
  - C
scalar_sse_features:
  - secondary_structure_one_hot
  - secondary_structure_length
vector_sse_features: []

